## Database Properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/importer?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 40
      minimum-idle: 20
      #leak-detection-threshold: 30000
  output:
    ansi:
      enabled: always #Habilita as cores no console
  liquibase:
    change-log: classpath:db/changelog-master.xml

  ## Hibernate Properties
  jpa:
    hibernate:
      #Valida na inicialização do sistema, se o JPA conseguirá se comunicar com as entidades definidas
      ddl-auto: validate
      naming:
        #Para encontrar tabelas uppercase no banco de dados, por padrão o hibernate busca tudo com lowercase
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

#logging:
#  level:
#    #Habilita informações sobre o hikari, como o tamanho do pool atual
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE
