## Database Properties
spring:
  datasource:
    hikari:
      maximum-pool-size: 40
      minimum-idle: 20
      #leak-detection-threshold: 30000
  output:
    ansi:
      enabled: always #Habilita as cores no console
  liquibase:
    change-log: classpath:db/changelog-master.xml

  ## Hibernate Properties
  jpa:
    hibernate:
      #Valida na inicialização do sistema, se o JPA conseguirá se comunicar com as entidades definidas
      ddl-auto: validate
      naming:
        #Para encontrar tabelas uppercase no banco de dados, por padrão o hibernate busca tudo com lowercase
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
