name: CI - Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  show-environment-specs:
    name: Showing environment specifications
    runs-on: ubuntu-latest
    steps:
      - name: Show VM CPU specs
        run: lscpu

      - name: Show VM RAM specs
        run: free -m

      - name: Show VM HD specs
        run: lsblk

  build:
    name: Building project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v4
    
    - name: Set up JDK 17 temurin
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn package -B -DskipTests

  test:
    name: Testing project
    runs-on: ubuntu-latest
    needs: build

    #Example https://github.com/norio-io/example-github-actions-with-ephemeral-mysql/blob/main/.github/workflows/example.yml
    services:
      db:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
    - name: Checkout Actions
      uses: actions/checkout@v4

    - name: Set up JDK 17 temurin
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: JUnit tests
      run: mvn test -B -Dmaven.test.failure.ignore=true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Reporting JUnit tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true

  update-dependency-graph:
    name: Updating dependency graph
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v4

    - name: Set up JDK 17 temurin
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4
